CREATE TABLE TBL_ALUMNO
(
	PK_IDALUMNO int primary key identity(1,1),
	ALU_NOMBRE nvarchar(20),
	ALU_APELLIDO nvarchar(20),
	FK_IDCURSO int,
	ALU_FECHA_CREACION datetime default getdate(),
	ALU_ACTIVO int
)



GO
CREATE TABLE TBL_CURSO
(
	PK_IDCURSO int primary key identity(1,1),
	CUR_GRADO int,
	CUR_DESCRIPCION nvarchar(20)
)
GO
CREATE TABLE TBL_MATERIA
(
	PK_IDMATERIA int primary key identity(1,1),
	MAT_NOMBRE nvarchar(20)
)
GO
CREATE TABLE TBL_NOTA
(
	PK_IDNOTA int primary key identity(1,1),
	NOT_VALOR int,
	FK_IDMATERIA int,
	FK_IDALUMNO int,
	FK_PERIODO int
)
CREATE TABLE TBL_PERIODO
(
	PK_IDPERIODO int primary key identity(1,1),
	PERIODO int
)


ALTER TABLE TBL_NOTA
ADD CONSTRAINT NOTA__MATERIA_ALUMNO_PERIODO UNIQUE (FK_IDMATERIA,FK_IDALUMNO,FK_PERIODO)


ALTER TABLE TBL_NOTA
ADD FOREIGN KEY (FK_PERIODO) REFERENCES TBL_PERIODO(PK_IDPERIODO);


ALTER TABLE TBL_ALUMNO
ADD FOREIGN KEY (FK_IDCURSO) REFERENCES TBL_CURSO(PK_IDCURSO);

ALTER TABLE TBL_NOTA
ADD FOREIGN KEY (FK_IDMATERIA) REFERENCES TBL_MATERIA(PK_IDMATERIA);

ALTER TABLE TBL_NOTA
ADD FOREIGN KEY (FK_IDALUMNO) REFERENCES TBL_ALUMNO(PK_IDALUMNO);


INSERT INTO TBL_CURSO
VALUES(1,'PRIMERO'),(2,'SEGUNDO'),(3,'TERCERO'),(4,'CUARTO'),(5,'QUINTO')

INSERT INTO TBL_ALUMNO (ALU_NOMBRE,ALU_APELLIDO,FK_IDCURSO)
VALUES('William','Ramirez',5),('Carlos','Molano',5),('Laura','Rodriguez',5),('Lucia','Morales',4),('Felipe','Mora',4)


INSERT INTO TBL_MATERIA
VALUES ('MATEMÁTICA'),('INGLES'),('ESPAÑOL'),('BIOLOGÍA'),('SOCIALES')

INSERT INTO [dbo].[TBL_PERIODO]
VALUES (1),(2),(3)